name: PythonAppTest

on:
  workflow_dispatch:

jobs:
  numpy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Python
        run: python src/imageload_test.py

      - name: Check for changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
  
          git diff --quiet || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
  
      - name: Create Pull Request
        if: env.CHANGES_DETECTED == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "update/scraping-data"
          title: "Update scraping data (Automated)"
          body: |
            This pull request updates the scraping data.
            - Automated update from GitHub Actions.
          commit-message: "Update scraping data"
          base: "master"
          delete-branch: true
          labels: "automated update"
